name: ourtown
version: ${version}
main: cat.nyaa.ourtown.OurTown
depend: [NyaaCore,Essentials]
softdepend: [HamsterEcoHelper]
authors: [cylin]
api-version: 1.13
commands:
  town:
permissions:
  town.player.select:
    description: Select a spawn point
    default: true
  town.player.tp:
    description: Teleport to spawn point
    default: true
  town.admin:
    default: op
