name: ourtown
version: ${version}
main: cat.nyaa.ourtown.OurTown
depend: [ NyaaCore,Essentials,ECore ]
authors: [ cylin ]
api-version: 1.13
commands:
  town:
    description: "our town"
  home:
    description: "your home"
  sethome:
    description: "set your home"
  back:
    description: "go back"
permissions:
  town.player.select:
    description: Select a spawn point
    default: true
  town.player.tp:
    description: Teleport to spawn point
    default: true
  town.admin:
    default: op
